services:
    RollandRock\WebsocketBundle\Command\ServerCommand:
        autoconfigure: true
    RollandRock\WebsocketBundle\Handler\HandlerRegistry: ~
    RollandRock\WebsocketBundle\Websocket:
        public: true
        autowire: true
        arguments:
            $clientClass: "%rr_ws_client%"
